from pathlib import Path

APP = Path('app.py')
text = APP.read_text(encoding='utf-8')
start = text.index("LOGIN_HTML = '''")
end = text.index("\n\nUSERS_HTML = '''", start)

html = """<!doctype html><html lang="pt-br"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Acesso | Sakamoto</title>
<style>
*{box-sizing:border-box}body{margin:0;min-height:100vh;font-family:Inter,Arial,sans-serif;background:radial-gradient(circle at 50% 20%,#163b0b 0,#071507 45%,#020602 100%);display:grid;place-items:center;color:#fff;overflow:hidden}body:before{content:"";position:fixed;inset:0;background:linear-gradient(135deg,transparent 45%,rgba(103,255,0,.08) 46%,transparent 47%),linear-gradient(315deg,transparent 45%,rgba(255,220,0,.06) 46%,transparent 47%);background-size:80px 80px;pointer-events:none}.box{position:relative;width:min(420px,92vw);padding:34px 34px 30px;border:1px solid rgba(139,255,35,.28);border-radius:24px;background:rgba(5,14,5,.88);box-shadow:0 0 55px rgba(85,255,0,.16),0 24px 70px rgba(0,0,0,.5);backdrop-filter:blur(12px);text-align:center}.logo{width:210px;height:210px;object-fit:contain;border-radius:18px;margin:-10px auto 8px;display:block;filter:drop-shadow(0 0 18px rgba(120,255,0,.25))}.title{font-size:25px;font-weight:800;letter-spacing:1px;margin:4px 0;color:#ffd900}.subtitle{font-size:12px;letter-spacing:3px;color:#61ff18;margin-bottom:24px}.field{text-align:left;margin:13px 0}.field label{display:block;font-size:12px;color:#b7c9b0;margin-bottom:6px}.field input{width:100%;padding:14px 15px;border:1px solid #29442a;border-radius:12px;background:#0b180b;color:#fff;outline:none}.field input:focus{border-color:#61ff18;box-shadow:0 0 0 3px rgba(97,255,24,.1)}button{width:100%;padding:14px;margin-top:12px;border:0;border-radius:12px;background:linear-gradient(90deg,#ffd500,#75ff16);color:#071000;font-weight:900;font-size:15px;cursor:pointer;box-shadow:0 8px 25px rgba(126,255,0,.18)}button:hover{transform:translateY(-1px)}.flash{background:#3a1515;color:#ffb8b8;border:1px solid #6e2a2a;padding:10px;border-radius:10px;font-size:13px}.footer{margin-top:22px;font-size:11px;color:#789074}
</style></head><body><div class="box"><img class="logo" src="/static/logo.svg" alt="Sakamoto Variedades e Tecnologia"><div class="title">SAKAMOTO</div><div class="subtitle">VARIEDADES E TECNOLOGIA</div>{% for m in get_flashed_messages() %}<p class="flash">{{m}}</p>{% endfor %}<form method="post"><div class="field"><label>USUÁRIO</label><input name="username" placeholder="Digite seu usuário" autocomplete="username" required></div><div class="field"><label>SENHA</label><input type="password" name="password" placeholder="Digite sua senha" autocomplete="current-password" required></div><button type="submit">ENTRAR NO SISTEMA</button></form><div class="footer">Acesso seguro • Sistema de Manutenção</div></div></body></html>"""

replacement = "LOGIN_HTML = '''" + html + "'''"
APP.write_text(text[:start] + replacement + text[end:], encoding='utf-8')
print('Login atualizado com a identidade visual Sakamoto.')
