services:
  - type: web
    name: sistema-manutencao-sakamoto
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn photo_app:app
    healthCheckPath: /status
    autoDeploy: true
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: sakamoto-db
          property: connectionString

databases:
  - name: sakamoto-db
    databaseName: sakamoto
    user: sakamoto
    plan: free
